In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("learners.csv")

# Missing Values Per Columns

In [4]:
df.isnull().sum()

name           0
role           0
score          1
department     0
joined_year    0
dtype: int64

# After dropna

In [16]:
df_dropped = df.dropna()

In [17]:
df_dropped.isnull().sum()

name           0
role           0
score          0
department     0
joined_year    0
dtype: int64

# fillna

In [18]:
df_filled = df.copy()
df_filled["score"] = df_filled["score"].fillna(df_filled["score"].mean())

In [19]:
df_filled.isnull().sum()

name           0
role           0
score          0
department     0
joined_year    0
dtype: int64

# Before vs After

In [20]:
df

             name     role  score   department  joined_year
0   Harsh Patidar   Intern   95.0  Engineering         2024
1  Gaurav Dwivedi   Intern   88.0  Engineering         2024
2   Dheeraj Saini  Analyst   82.0    Marketing         2023
3     Priya Mehta  Analyst   76.0      Finance         2023
4       Rohan Das   Intern   91.0  Engineering         2024
5     Sneha Joshi  Manager   85.0           HR         2022
6     Karan Patel  Analyst   70.0      Finance         2023
7      Amit Verma  Manager    NaN    Marketing         2021
8      Raj Kapoor   Intern   78.0           HR         2024
9      Neha Gupta  Manager   88.0  Engineering         2022

In [21]:
df_filled

             name     role      score   department  joined_year
0   Harsh Patidar   Intern  95.000000  Engineering         2024
1  Gaurav Dwivedi   Intern  88.000000  Engineering         2024
2   Dheeraj Saini  Analyst  82.000000    Marketing         2023
3     Priya Mehta  Analyst  76.000000      Finance         2023
4       Rohan Das   Intern  91.000000  Engineering         2024
5     Sneha Joshi  Manager  85.000000           HR         2022
6     Karan Patel  Analyst  70.000000      Finance         2023
7      Amit Verma  Manager  83.666667    Marketing         2021
8      Raj Kapoor   Intern  78.000000           HR         2024
9      Neha Gupta  Manager  88.000000  Engineering         2022

In [22]:
df_dropped

             name     role  score   department  joined_year
0   Harsh Patidar   Intern   95.0  Engineering         2024
1  Gaurav Dwivedi   Intern   88.0  Engineering         2024
2   Dheeraj Saini  Analyst   82.0    Marketing         2023
3     Priya Mehta  Analyst   76.0      Finance         2023
4       Rohan Das   Intern   91.0  Engineering         2024
5     Sneha Joshi  Manager   85.0           HR         2022
6     Karan Patel  Analyst   70.0      Finance         2023
8      Raj Kapoor   Intern   78.0           HR         2024
9      Neha Gupta  Manager   88.0  Engineering         2022