In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("learners.csv")
df.head()

             name     role  score   department  joined_year
0   Harsh Patidar   Intern   95.0  Engineering         2024
1  Gaurav Dwivedi   Intern   88.0  Engineering         2024
2   Dheeraj Saini  Analyst   82.0    Marketing         2023
3     Priya Mehta  Analyst   76.0      Finance         2023
4       Rohan Das   Intern   91.0  Engineering         2024

In [4]:
subset = df[["name", "role", "score"]]
subset.sample()

         name     role  score
7  Amit Verma  Manager    NaN

In [9]:
filtered = subset[df["role"] == "Intern"]
print("Filter: role == Intern") # this filter is printing only those values in which learners are intern
filtered

Filter: role == Intern

             name    role  score
0   Harsh Patidar  Intern   95.0
1  Gaurav Dwivedi  Intern   88.0
4       Rohan Das  Intern   91.0
8      Raj Kapoor  Intern   78.0

In [10]:
filtered2 = subset[df["score"] >= 85]
print("\nFilter: score >= 85") # THis filter is printing rows where score is 85 or more
filtered2

Filter: score >= 85

             name     role  score
0   Harsh Patidar   Intern   95.0
1  Gaurav Dwivedi   Intern   88.0
4       Rohan Das   Intern   91.0
5     Sneha Joshi  Manager   85.0
9      Neha Gupta  Manager   88.0